name: Terraform CI

on:
  push:
    branches:
      - main  # Only run on changes to main branch
  pull_request:
    branches:
      - main  # Run plan on pull requests to main

jobs:
  terraform:
    name: 'Terraform Plan & Apply'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.0  # Use correct version or your preferred one

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan

    # ⚠️ Optional: Uncomment this if you want to apply automatically (only if safe)
    # - name: Terraform Apply
    #   run: terraform apply -auto-approve
